import {NextResponse} from "next/server";
import {currentUser} from "@/lib/auth";
import {prisma} from "@/lib/prisma";
import {z} from "zod";

const input=z.object({startsAt:z.string().min(1),endsAt:z.string().optional().nullable(),flow:z.enum(["Hafif","Orta","Yoğun"]).optional().nullable(),symptoms:z.array(z.string().trim().min(1).max(60)).max(20).default([]),note:z.string().trim().max(1000).optional().nullable()});
export async function GET(){const u=await currentUser();if(!u)return NextResponse.json({error:"Giriş gerekli"},{status:401});return NextResponse.json(await prisma.menstrualCycleRecord.findMany({where:{userId:u.id},orderBy:{startsAt:"desc"},take:36}))}
export async function POST(req:Request){const u=await currentUser();if(!u)return NextResponse.json({error:"Giriş gerekli"},{status:401});const parsed=input.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:"Geçersiz döngü kaydı",details:parsed.error.flatten()},{status:400});const b=parsed.data;const startsAt=new Date(`${b.startsAt}T12:00:00`),endsAt=b.endsAt?new Date(`${b.endsAt}T12:00:00`):null;if(Number.isNaN(startsAt.getTime())||(endsAt&&Number.isNaN(endsAt.getTime())))return NextResponse.json({error:"Geçersiz tarih"},{status:400});if(endsAt&&endsAt<startsAt)return NextResponse.json({error:"Bitiş tarihi başlangıçtan önce olamaz"},{status:400});return NextResponse.json(await prisma.menstrualCycleRecord.create({data:{userId:u.id,startsAt,endsAt,flow:b.flow||null,symptoms:b.symptoms,note:b.note||null}}),{status:201})}
export async function DELETE(req:Request){const u=await currentUser();if(!u)return NextResponse.json({error:"Giriş gerekli"},{status:401});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Kayıt id gerekli"},{status:400});const result=await prisma.menstrualCycleRecord.deleteMany({where:{id,userId:u.id}});if(!result.count)return NextResponse.json({error:"Kayıt bulunamadı"},{status:404});return NextResponse.json({ok:true})}
