"use client";
import SectionVisual from "@/components/section-visual";
import Link from "next/link";
import {useEffect,useState} from "react";import HealthIntegrations from "@/components/health-integrations";import HealthSharing from "@/components/health-sharing";import CarePlans from "@/components/care-plans";import {healthMetrics} from "@/lib/demo-data";import {Activity,FileText,HeartPulse,Plus,Trash2} from "@/components/icons";
type Doc={id:string;title:string;fileName:string;category:string;createdAt:string};type Lab={id:string;testName:string;value:string;unit?:string;reference?:string;status:string;measuredAt:string};
export default function Health(){const [entries,setEntries]=useState(healthMetrics),[open,setOpen]=useState(false),[docs,setDocs]=useState<Doc[]>([]),[labs,setLabs]=useState<Lab[]>([]),[docOpen,setDocOpen]=useState(false),[labOpen,setLabOpen]=useState(false),[message,setMessage]=useState('');const load=()=>{fetch('/api/health/documents').then(r=>r.ok?r.json():[]).then(setDocs);fetch('/api/health/labs').then(r=>r.ok?r.json():[]).then(setLabs)};useEffect(()=>{load()},[]);function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setEntries([{type:String(f.get('type')),value:String(f.get('value')),unit:String(f.get('unit')),status:'Yeni',trend:'Şimdi'},...entries]);setOpen(false)}async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const fileInput=f.querySelector('input[type="file"]') as HTMLInputElement;if(fileInput?.files?.[0]&&fileInput.files[0].size>4.5*1024*1024){setMessage('Dosya boyutu çok büyük (Maksimum 4.5 MB yüklenebilir).');return}setMessage('Yükleniyor...');try{const r=await fetch('/api/health/documents',{method:'POST',body:new FormData(f)});if(r.status===413){setMessage('Dosya boyutu çok büyük (Vercel sınırı 4.5 MB).');return}if(!r.ok){const t=await r.text();try{const j=JSON.parse(t);setMessage(j.error||'Yükleme başarısız')}catch{setMessage(`Sunucu hatası (${r.status})`)}return}await r.json();setMessage('Belge kaydedildi.');setDocOpen(false);load()}catch(err:any){setMessage(err.message||'Bir hata oluştu.')}}async function addLab(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body=Object.fromEntries(f.entries());const r=await fetch('/api/health/labs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok){setLabOpen(false);load()}}async function deleteLab(id:string){if(!confirm("Emin misiniz?"))return;await fetch(`/api/health/labs/${id}`,{method:"DELETE"});load()}async function deleteDoc(id:string){if(!confirm("Emin misiniz?"))return;await fetch(`/api/health/documents/${id}`,{method:"DELETE"});load()}
return <div className="page"><SectionVisual slug="health" alt="Sağlığım"/><div className="page-title row between"><div><span className="kicker">Kişisel alan</span><h1>Sağlığım</h1><p>Ölçümlerini, laboratuvar sonuçlarını ve belgelerini tek yerde tut.</p></div><button className="icon-button" onClick={()=>setOpen(!open)}><Plus/></button></div>{open&&<form className="inline-form" onSubmit={add}><input name="type" placeholder="Ölçüm (örn. Glukoz)" required/><input name="value" placeholder="Değer" required/><input name="unit" placeholder="Birim"/><button className="primary">Kaydet</button></form>}
<section className="health-quick-actions" style={{display: 'flex', gap: '12px', marginBottom: '24px', flexWrap: 'wrap'}}>
  <Link href="/services" className="secondary compact" style={{borderRadius: '20px', display: 'flex', alignItems: 'center', gap: '6px', fontWeight: 600}}>
    Tüm Hizmetler →
  </Link>
  <Link href="/health/blood-pressure" className="secondary compact" style={{borderRadius: '20px', background: '#f8fafc', border: '1px solid #e2e8f0'}}>+ Tansiyon</Link>
  <Link href="/health/glucose" className="secondary compact" style={{borderRadius: '20px', background: '#f8fafc', border: '1px solid #e2e8f0'}}>+ Şeker</Link>
  <Link href="/health/body" className="secondary compact" style={{borderRadius: '20px', background: '#f8fafc', border: '1px solid #e2e8f0'}}>+ Kilo</Link>
</section>
<div className="health-grid">{entries.map((m,i)=><div className="health-card" key={m.type+i}><div className="health-icon">{i%2?<Activity/>:<HeartPulse/>}</div><span>{m.type}</span><strong>{m.value} <small>{m.unit}</small></strong><div className="row between"><em>{m.status}</em><small>{m.trend}</small></div></div>)}</div><section className="panel health-section"><div className="row between"><div><h2>Laboratuvar sonuçları</h2><p>Sonuçlarını referans aralığıyla birlikte takip et.</p></div><button className="secondary" onClick={()=>setLabOpen(!labOpen)}>Sonuç ekle</button></div>{labOpen&&<form className="inline-form lab-form" onSubmit={addLab}><input name="testName" placeholder="Test (örn. Ferritin)" required/><input name="value" placeholder="Sonuç" required/><input name="unit" placeholder="Birim"/><input name="reference" placeholder="Referans"/><select name="status"><option value="normal">Normal</option><option value="low">Düşük</option><option value="high">Yüksek</option></select><button className="primary">Kaydet</button></form>}<div className="lab-list">{labs.map(l=><div className="lab-row" key={l.id}><div><b>{l.testName}</b><span>{new Date(l.measuredAt).toLocaleDateString('tr-TR')}</span></div><strong>{l.value} {l.unit}</strong><span>{l.reference||'—'}</span><div className="row"><em className={`lab-${l.status}`}>{l.status==='normal'?'Normal':l.status==='high'?'Yüksek':'Düşük'}</em><button className="icon-button text-red" onClick={()=>deleteLab(l.id)}><Trash2 size={16}/></button></div></div>)}{!labs.length&&<div className="empty">Henüz laboratuvar sonucu yok.</div>}</div></section><section className="panel health-section"><div className="row between"><div className="row"><FileText/><div><h2>Sağlık belgeleri</h2><p>PDF, JPG ve PNG raporlarını sakla.</p></div></div><button className="secondary" onClick={()=>setDocOpen(!docOpen)}>Belge ekle</button></div>{docOpen&&<form className="upload-form" onSubmit={upload}><input name="title" placeholder="Belge başlığı" required/><select name="category"><option value="lab">Laboratuvar</option><option value="report">Rapor</option><option value="imaging">Görüntüleme</option></select><input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required/><button className="primary">Yükle</button></form>}{message&&<div className="inline-message">{message}</div>}<div className="doc-list">{docs.map(d=><div className="doc-row" key={d.id}><FileText size={18}/><div style={{flex:1}}><b>{d.title}</b><span>{d.fileName} · {new Date(d.createdAt).toLocaleDateString('tr-TR')}</span></div><a className="secondary compact" href={`/api/health/documents/${d.id}`} target="_blank" rel="noopener noreferrer">Görüntüle / İndir</a><button className="icon-button text-red" onClick={()=>deleteDoc(d.id)}><Trash2 size={16}/></button></div>)}{!docs.length&&<div className="empty">Henüz belge yüklenmedi.</div>}</div></section><HealthIntegrations/><HealthSharing/><CarePlans/></div>}
