import { PrismaClient } from "@prisma/client"; import { pbkdf2Sync, randomBytes } from "node:crypto";
const prisma=new PrismaClient();
function hashPassword(password:string){const salt=randomBytes(16).toString('hex');return `${salt}:${pbkdf2Sync(password,salt,210000,32,'sha256').toString('hex')}`}
const doctors=[
{slug:"dr-aylin-kaya",name:"Dr. Aylin Kaya",title:"Uzm. Dr.",specialty:"İç Hastalıkları",hospital:"Alumas Sağlık Ağı",city:"İstanbul",rating:4.9,reviewCount:184,bio:"Koruyucu sağlık, metabolik takip ve kronik hastalık yönetimi alanlarında çalışan iç hastalıkları uzmanı.",price:1450,nextSlot:"Bugün 18:30",email:"aylin@alumas.app"},
{slug:"dr-kerem-demir",name:"Dr. Kerem Demir",title:"Doç. Dr.",specialty:"Kardiyoloji",hospital:"Alumas Sağlık Ağı",city:"İstanbul",rating:4.8,reviewCount:132,bio:"Kalp sağlığı, hipertansiyon ve uzaktan hasta takibi üzerine çalışan kardiyoloji uzmanı.",price:1800,nextSlot:"Yarın 10:00",email:"kerem@alumas.app"},
{slug:"dr-selin-arslan",name:"Dr. Selin Arslan",title:"Uzm. Dr.",specialty:"Dermatoloji",hospital:"Alumas Sağlık Ağı",city:"İstanbul",rating:4.9,reviewCount:221,bio:"Klinik dermatoloji, saç ve cilt sağlığı alanlarında hasta odaklı takip sunar.",price:1600,nextSlot:"Yarın 14:30",email:"selin@alumas.app"}
];
async function main(){
 await prisma.session.deleteMany();
 await prisma.user.upsert({where:{email:'demo@alumas.app'},update:{passwordHash:hashPassword('Alumas123!'),role:'PATIENT'},create:{name:'Alumas Kullanıcısı',email:'demo@alumas.app',passwordHash:hashPassword('Alumas123!'),role:'PATIENT'}});
 await prisma.user.upsert({where:{email:'admin@alumas.app'},update:{passwordHash:hashPassword('Admin123!'),role:'ADMIN'},create:{name:'Alumas Admin',email:'admin@alumas.app',passwordHash:hashPassword('Admin123!'),role:'ADMIN'}});
 for(const d of doctors){const user=await prisma.user.upsert({where:{email:d.email},update:{name:d.name,passwordHash:hashPassword('Doctor123!'),role:'DOCTOR'},create:{name:d.name,email:d.email,passwordHash:hashPassword('Doctor123!'),role:'DOCTOR'}});const {email,...doc}=d;const doctor=await prisma.doctor.upsert({where:{slug:d.slug},update:{...doc,userId:user.id,isVerified:true,isPublished:true},create:{...doc,userId:user.id,isVerified:true,isPublished:true}});await prisma.availability.deleteMany({where:{doctorId:doctor.id}});for(let day=1;day<=7;day++){for(const hour of [10,14,16]){const s=new Date();s.setDate(s.getDate()+day);s.setHours(hour,0,0,0);const e=new Date(s.getTime()+30*60000);await prisma.availability.create({data:{doctorId:doctor.id,startsAt:s,endsAt:e,type:hour===16?'online':'both'}})}}}
 const patient=await prisma.user.findUniqueOrThrow({where:{email:'demo@alumas.app'}});const aylin=await prisma.doctor.findUniqueOrThrow({where:{slug:'dr-aylin-kaya'}});const firstSlot=await prisma.availability.findFirstOrThrow({where:{doctorId:aylin.id},orderBy:{startsAt:'asc'}});await prisma.appointment.deleteMany({where:{userId:patient.id,doctorId:aylin.id}});await prisma.appointment.create({data:{userId:patient.id,doctorId:aylin.id,startsAt:firstSlot.startsAt,type:'online',status:'confirmed',note:'Demo takip randevusu'}});const past=new Date(Date.now()-2*24*60*60*1000);await prisma.appointment.create({data:{userId:patient.id,doctorId:aylin.id,startsAt:past,type:'online',status:'completed',note:'Tamamlanmış demo görüşme',reviewRequestedAt:new Date(Date.now()-2*24*60*60*1000)}});await prisma.healthShareConsent.upsert({where:{patientId_doctorId:{patientId:patient.id,doctorId:aylin.id}},update:{status:'active',scopes:['measurements','labs','documents','imaging','care_plans']},create:{patientId:patient.id,doctorId:aylin.id,scopes:['measurements','labs','documents','imaging','care_plans']}});await prisma.carePlan.deleteMany({where:{patientId:patient.id,doctorId:aylin.id}});await prisma.carePlan.create({data:{patientId:patient.id,doctorId:aylin.id,title:'7 günlük koruyucu sağlık takibi',summary:'Günlük aktivite ve ölçüm takibi.',items:{create:[{kind:'activity',title:'Günlük yürüyüş',instructions:'Rahat tempoda yürüyüş',schedule:'Günde 30 dakika'},{kind:'measurement',title:'Tansiyon takibi',instructions:'Dinlenme sonrası ölç',schedule:'Sabah ve akşam'}]}}});
 const admin=await prisma.user.findUniqueOrThrow({where:{email:'admin@alumas.app'}});
 const hospital=await prisma.organization.upsert({where:{slug:'alumas-sehir-hastanesi'},update:{ownerUserId:admin.id,status:'APPROVED',isPublished:true,verifiedAt:new Date(),publishedAt:new Date(),latitude:40.9638,longitude:29.0632},create:{ownerUserId:admin.id,type:'HOSPITAL',status:'APPROVED',name:'Alumas Şehir Hastanesi',slug:'alumas-sehir-hastanesi',city:'İstanbul',district:'Kadıköy',address:'Bağdat Caddesi 100',phone:'+90 212 000 00 01',email:'hastane@alumas.app',description:'Çok branşlı doğrulanmış demo hastane.',isPublished:true,verifiedAt:new Date(),publishedAt:new Date(),latitude:40.9638,longitude:29.0632}});
 const dutyUntil=new Date(Date.now()+12*60*60*1000);const pharmacy=await prisma.organization.upsert({where:{slug:'alumas-merkez-eczanesi'},update:{ownerUserId:admin.id,status:'APPROVED',isPublished:true,verifiedAt:new Date(),publishedAt:new Date(),latitude:41.0431,longitude:29.0061,isOnDuty:true,onDutyUntil:dutyUntil},create:{ownerUserId:admin.id,type:'PHARMACY',status:'APPROVED',name:'Alumas Merkez Eczanesi',slug:'alumas-merkez-eczanesi',city:'İstanbul',district:'Beşiktaş',address:'Çarşı Caddesi 12',phone:'+90 212 000 00 02',email:'eczane@alumas.app',description:'Doğrulanmış demo eczane.',isPublished:true,verifiedAt:new Date(),publishedAt:new Date(),latitude:41.0431,longitude:29.0061,isOnDuty:true,onDutyUntil:dutyUntil}});
 const clinic=await prisma.organization.upsert({where:{slug:'alumas-saglik-klinigi'},update:{ownerUserId:patient.id,status:'PENDING',isPublished:false},create:{ownerUserId:patient.id,type:'CLINIC',status:'PENDING',name:'Alumas Sağlık Kliniği',slug:'alumas-saglik-klinigi',city:'İstanbul',district:'Şişli',address:'Sağlık Sokak 8',phone:'+90 212 000 00 03',email:'klinik@alumas.app',description:'Admin onayı bekleyen demo klinik.',isPublished:false}});
 await prisma.organizationService.deleteMany({where:{organizationId:{in:[hospital.id,pharmacy.id]}}});
 await prisma.organizationService.createMany({data:[{organizationId:hospital.id,name:'İç Hastalıkları Muayenesi',description:'Uzman hekim değerlendirmesi',price:1450},{organizationId:hospital.id,name:'Kardiyoloji Muayenesi',description:'Kalp ve tansiyon değerlendirmesi',price:1800},{organizationId:hospital.id,name:'Laboratuvar',description:'Temel kan tetkikleri'},{organizationId:pharmacy.id,name:'Reçete danışmanlığı',description:'Eczacı bilgilendirmesi'}]});
 for(const org of [hospital,pharmacy])for(let weekday=0;weekday<7;weekday++)await prisma.organizationHours.upsert({where:{organizationId_weekday:{organizationId:org.id,weekday}},update:{isClosed:weekday===0,opensAt:weekday===0?null:'09:00',closesAt:weekday===0?null:'19:00'},create:{organizationId:org.id,weekday,isClosed:weekday===0,opensAt:weekday===0?null:'09:00',closesAt:weekday===0?null:'19:00'}});
 await prisma.pharmacyStock.upsert({where:{organizationId_itemName:{organizationId:pharmacy.id,itemName:'Parasetamol 500 mg'}},update:{stockStatus:'in_stock',quantity:18},create:{organizationId:pharmacy.id,itemName:'Parasetamol 500 mg',stockStatus:'in_stock',quantity:18}});
 await prisma.pharmacyStock.upsert({where:{organizationId_itemName:{organizationId:pharmacy.id,itemName:'Vitamin D3'}},update:{stockStatus:'limited',quantity:4},create:{organizationId:pharmacy.id,itemName:'Vitamin D3',stockStatus:'limited',quantity:4}});
 await prisma.doctor.update({where:{id:aylin.id},data:{organizationId:hospital.id,hospital:hospital.name}});
 await prisma.organizationFavorite.upsert({where:{userId_organizationId:{userId:patient.id,organizationId:hospital.id}},update:{},create:{userId:patient.id,organizationId:hospital.id}});await prisma.doctorFavorite.upsert({where:{userId_doctorId:{userId:patient.id,doctorId:aylin.id}},update:{},create:{userId:patient.id,doctorId:aylin.id}});await prisma.doctorReview.upsert({where:{userId_doctorId:{userId:patient.id,doctorId:aylin.id}},update:{rating:5,comment:'Açıklayıcı ve düzenli bir görüşmeydi.',status:'APPROVED'},create:{userId:patient.id,doctorId:aylin.id,rating:5,comment:'Açıklayıcı ve düzenli bir görüşmeydi.',status:'APPROVED'}});
 await prisma.organizationReview.upsert({where:{userId_organizationId:{userId:patient.id,organizationId:hospital.id}},update:{rating:5,comment:'Demo değerlendirme: randevu süreci hızlı ve düzenliydi.',status:'APPROVED'},create:{userId:patient.id,organizationId:hospital.id,rating:5,comment:'Demo değerlendirme: randevu süreci hızlı ve düzenliydi.',status:'APPROVED'}});
 await prisma.appointment.updateMany({where:{userId:patient.id,doctorId:aylin.id},data:{organizationId:hospital.id}});

 await prisma.organizationDoctorInvite.deleteMany({where:{organizationId:clinic.id}});
 const kerem=await prisma.user.findUniqueOrThrow({where:{email:'kerem@alumas.app'}});const keremDoctor=await prisma.doctor.findUnique({where:{userId:kerem.id}});
 await prisma.organizationDoctorInvite.create({data:{organizationId:clinic.id,email:kerem.email,doctorUserId:kerem.id,doctorId:keremDoctor?.id||null,specialty:keremDoctor?.specialty||null,invitedById:patient.id,status:'PENDING'}});
 await prisma.medicationDoseLog.deleteMany({where:{userId:patient.id}});await prisma.healthTarget.deleteMany({where:{userId:patient.id}});await prisma.healthReminder.deleteMany({where:{userId:patient.id}});await prisma.medication.deleteMany({where:{userId:patient.id}});await prisma.bloodPressureReading.deleteMany({where:{userId:patient.id}});await prisma.glucoseReading.deleteMany({where:{userId:patient.id}});await prisma.sleepRecord.deleteMany({where:{userId:patient.id}});
 const now=new Date();for(let i=6;i>=0;i--){const d=new Date(now);d.setDate(d.getDate()-i);d.setHours(8,15,0,0);await prisma.bloodPressureReading.create({data:{userId:patient.id,systolic:118+(i%3)*2,diastolic:76+(i%2)*2,pulse:70+(i%4),measuredAt:d}});const g=new Date(d);g.setHours(7,45,0,0);await prisma.glucoseReading.create({data:{userId:patient.id,value:90+(i%4)*4,context:i%2===0?'FASTING':'POSTPRANDIAL',measuredAt:g}});const end=new Date(d);end.setHours(7,0,0,0);const start=new Date(end.getTime()-(6.8+(i%3)*0.35)*3600000);await prisma.sleepRecord.create({data:{userId:patient.id,startedAt:start,endedAt:end,quality:4+(i%2)}})}
 const med=await prisma.medication.create({data:{userId:patient.id,name:'Demo tansiyon ilacı',dose:'1 tablet',instructions:'Doktor önerisine göre kullanın.',times:['09:00','21:00'],isActive:true}});await prisma.healthReminder.createMany({data:[{userId:patient.id,kind:'BLOOD_PRESSURE',title:'Tansiyon ölçümü',timeOfDay:'09:00',weekdays:[0,1,2,3,4,5,6]},{userId:patient.id,medicationId:med.id,kind:'MEDICATION',title:'Demo tansiyon ilacı',timeOfDay:'21:00',weekdays:[0,1,2,3,4,5,6]},{userId:patient.id,kind:'GLUCOSE',title:'Kan şekeri ölçümü',timeOfDay:'07:45',weekdays:[1,3,5]}]});
 const todayKey=new Date().toISOString().slice(0,10);await prisma.medicationDoseLog.createMany({data:[{userId:patient.id,medicationId:med.id,scheduledFor:new Date(`${todayKey}T09:00:00.000Z`),status:'TAKEN'},{userId:patient.id,medicationId:med.id,scheduledFor:new Date(`${todayKey}T21:00:00.000Z`),status:'SKIPPED'}],skipDuplicates:true});
 await prisma.labResult.deleteMany({where:{userId:patient.id}});for(let i=3;i>=0;i--){const d=new Date(now);d.setMonth(d.getMonth()-i);await prisma.labResult.create({data:{userId:patient.id,testName:'Ferritin',normalizedName:'ferritin',panel:'Demir paneli',value:String(34+i*3),numericValue:34+i*3,unit:'ng/mL',referenceLow:15,referenceHigh:150,status:'normal',measuredAt:d}})}
 const ferritin=await prisma.labResult.findFirst({where:{userId:patient.id,testName:'Ferritin'},orderBy:{measuredAt:'desc'}});
 await prisma.labResultComment.deleteMany({where:{patientId:patient.id,doctorId:aylin.id}});if(ferritin)await prisma.labResultComment.create({data:{labResultId:ferritin.id,patientId:patient.id,doctorId:aylin.id,body:'Demo yorum: sonucu önceki ölçümler ve klinik durumla birlikte değerlendirelim.',patientVisible:true}});
 await prisma.patientDoctorQuestion.deleteMany({where:{patientId:patient.id,doctorId:aylin.id}});await prisma.patientDoctorQuestion.create({data:{patientId:patient.id,doctorId:aylin.id,subject:'Tansiyon ölçüm saatleri',body:'Sabah ölçümünü ilaçtan önce mi sonra mı kaydetmeliyim?',answer:'Takip planında konuştuğumuz ölçüm saatini koruyalım; özel talimat için reçete ve planını esas al.',status:'answered',answeredAt:new Date()}});
 await prisma.doctorPatientNote.deleteMany({where:{patientId:patient.id,doctorId:aylin.id}});await prisma.doctorPatientNote.create({data:{patientId:patient.id,doctorId:aylin.id,title:'Takip notu',body:'Demo takip notu. Bu not hasta ile paylaşılmıştır.',category:'followup',patientVisible:true}});
 await prisma.healthGoal.deleteMany({where:{userId:patient.id}});await prisma.healthGoal.create({data:{userId:patient.id,doctorId:aylin.id,title:'Haftada 4 gün yürüyüş',metric:'aktivite',targetValue:4,currentValue:2,progressPercent:50,unit:'gün/hafta',targetDate:new Date(Date.now()+30*86400000),note:'Bakım planı ile ortak hedef'}});
 const demoPlan=await prisma.carePlan.findFirst({where:{patientId:patient.id,doctorId:aylin.id}});await prisma.carePlanEvent.deleteMany({where:{patientId:patient.id,doctorId:aylin.id}});if(demoPlan)await prisma.carePlanEvent.create({data:{carePlanId:demoPlan.id,patientId:patient.id,doctorId:aylin.id,title:'Haftalık tansiyon kontrolü',kind:'measurement',startsAt:new Date(Date.now()+2*86400000),note:'Sabah ölçümlerini birlikte gözden geçir'}});

 await prisma.diagnosticRequest.deleteMany({where:{patientId:patient.id,doctorId:aylin.id}});await prisma.imagingResult.deleteMany({where:{userId:patient.id}});const img=await prisma.imagingResult.create({data:{userId:patient.id,title:'Diz MR',modality:'MR',bodyPart:'Sol diz',provider:'Alumas Şehir Hastanesi',performedAt:new Date(Date.now()-20*86400000),reportText:'Demo radyoloji raporu. Gerçek klinik yorum yerine geçmez.',impression:'Demo sonuç: takip eden hekimle birlikte değerlendirilmelidir.'}});await prisma.diagnosticRequest.create({data:{patientId:patient.id,doctorId:aylin.id,title:'Kontrol görüntüleme raporunu paylaş',category:'imaging',details:'Demo tetkik görevi',dueAt:new Date(Date.now()+5*86400000),status:'scheduled',imagingResultId:img.id}});await prisma.emergencyHealthCard.upsert({where:{userId:patient.id},update:{bloodType:'A Rh+',allergies:['Demo alerji bilgisi'],chronicConditions:[],medicationsSummary:['Demo tansiyon ilacı'],emergencyContactName:'Acil Yakın',emergencyContactPhone:'+90 5xx xxx xx xx',sharingEnabled:false},create:{userId:patient.id,bloodType:'A Rh+',allergies:['Demo alerji bilgisi'],chronicConditions:[],medicationsSummary:['Demo tansiyon ilacı'],emergencyContactName:'Acil Yakın',emergencyContactPhone:'+90 5xx xxx xx xx',sharingEnabled:false}});
 await prisma.healthSummaryShare.deleteMany({where:{patientId:patient.id}});await prisma.childGrowthRecord.deleteMany({where:{userId:patient.id}});await prisma.pregnancyEvent.deleteMany({where:{userId:patient.id}});await prisma.specialHealthProfile.deleteMany({where:{userId:patient.id}});
 const child=await prisma.specialHealthProfile.create({data:{userId:patient.id,type:'CHILD',name:'Deniz',relationLabel:'çocuğum',birthDate:new Date(Date.now()-4*365*86400000),notes:'Demo çocuk profili'}});for(const [months,h,w] of [[0,101,16.2],[2,102.5,16.8],[4,104,17.1]] as const){const d=new Date();d.setMonth(d.getMonth()-4+months);await prisma.childGrowthRecord.create({data:{userId:patient.id,specialProfileId:child.id,heightCm:h,weightKg:w,measuredAt:d}})}
 const pregnancy=await prisma.specialHealthProfile.create({data:{userId:patient.id,type:'PREGNANCY',name:'Gebelik takibim',startDate:new Date(Date.now()-90*86400000),dueDate:new Date(Date.now()+190*86400000),notes:'Demo gebelik takip profili'}});await prisma.pregnancyEvent.createMany({data:[{userId:patient.id,specialProfileId:pregnancy.id,title:'Kontrol randevusu',kind:'checkup',startsAt:new Date(Date.now()+7*86400000)},{userId:patient.id,specialProfileId:pregnancy.id,title:'Kişisel takip notlarını gözden geçir',kind:'reminder',startsAt:new Date(Date.now()+14*86400000)}]});
 await prisma.vaccinationRecord.deleteMany({where:{userId:patient.id}});const nextVaccine=new Date(Date.now()+21*86400000);await prisma.vaccinationRecord.create({data:{userId:patient.id,vaccineName:'Demo aşı kaydı',doseLabel:'Sonraki doz',administeredAt:new Date(Date.now()-180*86400000),nextDoseAt:nextVaccine,provider:'Demo sağlık kurumu',notes:'Gerçek aşı takvimi değildir.'}});const vdStart=new Date(nextVaccine);vdStart.setHours(0,0,0,0);const vdEnd=new Date(nextVaccine);vdEnd.setHours(23,59,59,999);await prisma.healthReminder.create({data:{userId:patient.id,kind:'VACCINATION',title:'Demo aşı kaydı · sonraki doz',timeOfDay:'09:00',weekdays:[nextVaccine.getDay()],startsOn:vdStart,endsOn:vdEnd}});
 await prisma.healthSummaryShare.create({data:{patientId:patient.id,doctorId:aylin.id,sections:['allergies','medications','vaccinations','measurements']}});

 await prisma.waterIntake.deleteMany({where:{userId:patient.id}});await prisma.waterIntake.createMany({data:[{userId:patient.id,amountMl:250,consumedAt:new Date()},{userId:patient.id,amountMl:330,consumedAt:new Date(Date.now()-2*3600000)},{userId:patient.id,amountMl:500,consumedAt:new Date(Date.now()-5*3600000)}]});
 await prisma.bodyMeasurement.deleteMany({where:{userId:patient.id}});await prisma.bodyMeasurement.createMany({data:[{userId:patient.id,weightKg:74.8,heightCm:178,waistCm:86,measuredAt:new Date(Date.now()-30*86400000)},{userId:patient.id,weightKg:74.2,heightCm:178,waistCm:85.5,measuredAt:new Date()}]});
 await prisma.menstrualCycleRecord.deleteMany({where:{userId:patient.id}});
 await prisma.insuranceProvider.upsert({where:{slug:'alumas-demo-sigorta'},update:{},create:{name:'Alumas Demo Sigorta',slug:'alumas-demo-sigorta',phone:'+90 212 000 10 10',description:'Demo sigorta sağlayıcısı. Kapsam ve provizyon bilgisi sağlayıcıdan doğrulanmalıdır.'}});
 await prisma.healthTourismPackage.upsert({where:{slug:'istanbul-checkup-demo'},update:{},create:{title:'İstanbul Check-up Destek Paketi',slug:'istanbul-checkup-demo',category:'Check-up',city:'İstanbul',providerName:'Alumas Şehir Hastanesi',languages:['Türkçe','English'],includes:['Koordinasyon','Tercüman desteği','Transfer planlama'],startingPrice:650,currency:'EUR',description:'Demo sağlık turizmi paketi; tıbbi uygunluk değerlendirmesi değildir.'}});
 await prisma.emergencyDirectoryItem.deleteMany();await prisma.emergencyDirectoryItem.createMany({data:[{kind:'EMERGENCY_LINE',name:'112 Acil Çağrı Merkezi',phone:'112',city:'Türkiye',note:'Acil durumlar için resmi çağrı hattı.'},{kind:'EMERGENCY_DEPARTMENT',name:'Alumas Şehir Hastanesi Acil',phone:'+90 212 000 00 01',city:'İstanbul',district:'Kadıköy',latitude:40.9638,longitude:29.0632,note:'Demo kurum kaydı.'}]});

// v26 coverage completion seeds
if(!await prisma.homeBanner.findFirst({where:{title:"Sağlığın için tek platform"}}))await prisma.homeBanner.create({data:{title:"Sağlığın için tek platform",subtitle:"Randevu, sağlık takibi ve kurum keşfi Alumas’ta bir arada.",ctaLabel:"Sağlığımı aç",ctaHref:"/health",background:"#DED7FF",sortOrder:1}});
await prisma.contentCategory.upsert({where:{slug:"saglik-hizmetleri"},update:{},create:{name:"Sağlık Hizmetleri",slug:"saglik-hizmetleri",kind:"service",templateKey:"health-service",description:"Doktor, kurum, evde sağlık ve acil hizmet kategorileri."}});
const hosp26=await prisma.organization.findFirst({where:{slug:"alumas-sehir-hastanesi"}});if(hosp26){if(!await prisma.organizationEmergencyService.findFirst({where:{organizationId:hosp26.id,name:"7/24 Acil Servis"}}))await prisma.organizationEmergencyService.create({data:{organizationId:hosp26.id,name:"7/24 Acil Servis",kind:"EMERGENCY_DEPARTMENT",phone:hosp26.phone,is24Hours:true,description:"Demo hastane acil servis birimi."}});const firstSvc=await prisma.organizationService.findFirst({where:{organizationId:hosp26.id}});if(firstSvc&&!await prisma.serviceVariant.findFirst({where:{serviceId:firstSvc.id,label:"Online ön görüşme"}}))await prisma.serviceVariant.create({data:{serviceId:firstSvc.id,label:"Online ön görüşme",priceDelta:0,durationMinutes:20}})}
if(!await prisma.emergencyProvider.findFirst({where:{name:"Alumas Ambulans Koordinasyon"}}))await prisma.emergencyProvider.create({data:{kind:"AMBULANCE",name:"Alumas Ambulans Koordinasyon",phone:"+90 212 555 1122",city:"İstanbul",district:"Kadıköy",latitude:40.966,longitude:29.06,is24Hours:true,isVerified:true,description:"Demo ambulans hizmet sağlayıcı kaydı. Hayati acilde 112 kullanılmalıdır."}});
if(!await prisma.emergencyProvider.findFirst({where:{name:"Alumas Acil Danışmanlık"}}))await prisma.emergencyProvider.create({data:{kind:"EMERGENCY_CONSULT",name:"Alumas Acil Danışmanlık",phone:"+90 212 555 1133",city:"İstanbul",is24Hours:true,isVerified:true,description:"Demo sağlık danışmanlığı; acil çağrı hattı değildir."}});
const ag26=await prisma.healthTourismAgency.upsert({where:{slug:"alumas-global-care"},update:{isVerified:true,status:"APPROVED",isActive:true},create:{name:"Alumas Global Care",slug:"alumas-global-care",city:"İstanbul",phone:"+90 212 555 4400",email:"global@alumas.app",languages:["Türkçe","English","Deutsch","العربية"],description:"Tedavi yolculuğunda koordinasyon, transfer ve konaklama desteği sağlayan örnek acente profili.",isVerified:true,status:"APPROVED",isActive:true}});if(ag26){for(const x of [{kind:"TRANSFER",title:"Havalimanı ve kurum transferi",description:"Havalimanı, otel ve sağlık kurumu arasında planlama."},{kind:"ACCOMMODATION",title:"Konaklama koordinasyonu",description:"Anlaşmalı konaklama seçenekleri."},{kind:"TRANSLATION",title:"Tercüman desteği",description:"Randevu ve kurum iletişiminde dil desteği."},{kind:"REFERRAL",title:"Partner acente yönlendirmesi",description:"Gerekli olduğunda doğrulanmış partner hizmet ağına koordineli yönlendirme.",partnerAgencyName:"Demo Partner Health"}] as any[]){if(!await prisma.healthTourismAgencyService.findFirst({where:{agencyId:ag26.id,kind:x.kind,title:x.title}}))await prisma.healthTourismAgencyService.create({data:{agencyId:ag26.id,...x}})}}

 console.log('Alumas demo verileri hazır. Hasta: demo@alumas.app / Alumas123! | Doktor: aylin@alumas.app / Doctor123! | Admin: admin@alumas.app / Admin123!');

// v25 category completion seeds
const hospitalV25=await prisma.organization.findFirst({where:{slug:'alumas-sehir-hastanesi'}});
if(hospitalV25){
  const cardio=await prisma.organizationDepartment.upsert({where:{organizationId_name:{organizationId:hospitalV25.id,name:'Kardiyoloji'}},update:{},create:{organizationId:hospitalV25.id,name:'Kardiyoloji',floor:'2. Kat',phone:'Dahili 220',description:'Kalp ve damar sağlığı değerlendirme birimi.'}});
  const internal=await prisma.organizationDepartment.upsert({where:{organizationId_name:{organizationId:hospitalV25.id,name:'İç Hastalıkları'}},update:{},create:{organizationId:hospitalV25.id,name:'İç Hastalıkları',floor:'1. Kat',phone:'Dahili 110'}});
  const docs=await prisma.doctor.findMany({where:{organizationId:hospitalV25.id}});for(const d of docs){await prisma.doctor.update({where:{id:d.id},data:{departmentId:d.specialty.toLocaleLowerCase('tr-TR').includes('kard')?cardio.id:internal.id}})}
  if(!await prisma.organizationCampaign.findFirst({where:{organizationId:hospitalV25.id,title:'Online kontrol görüşmesi'}}))await prisma.organizationCampaign.create({data:{organizationId:hospitalV25.id,title:'Online kontrol görüşmesi',description:'Uygun uzman ve randevu koşulları için kurum profilini inceleyin.',startsAt:new Date(),endsAt:new Date(Date.now()+45*86400000)}});
}
const dir112=await prisma.emergencyDirectoryItem.findFirst({where:{phone:'112'}});if(!dir112)await prisma.emergencyDirectoryItem.create({data:{kind:'ACIL',name:'112 Acil Çağrı Merkezi',phone:'112',note:'Türkiye resmi acil çağrı hattı'}});
const favHospital=await prisma.emergencyDirectoryItem.findFirst({where:{name:'Alumas Şehir Hastanesi Santral'}});if(!favHospital)await prisma.emergencyDirectoryItem.create({data:{kind:'HASTANE',name:'Alumas Şehir Hastanesi Santral',phone:'+90 212 555 0101',city:'İstanbul'}});
const agency=await prisma.healthTourismAgency.upsert({where:{slug:'alumas-global-care'},update:{isVerified:true,status:'APPROVED',isActive:true},create:{name:'Alumas Global Care',slug:'alumas-global-care',city:'İstanbul',phone:'+90 212 555 4400',email:'global@alumas.app',languages:['Türkçe','English','Deutsch','العربية'],description:'Tedavi yolculuğunda kurum koordinasyonu, transfer ve konaklama desteği sağlayan örnek acente profili.',isVerified:true,status:'APPROVED',isActive:true}});
const pkg=await prisma.healthTourismPackage.findFirst({where:{isPublished:true}});if(pkg)await prisma.healthTourismPackage.update({where:{id:pkg.id},data:{agencyId:agency.id,transferIncluded:true,accommodationIncluded:true,airportPickup:true,coordinatorSupport:true,transferNotes:'Havalimanı–otel–kurum transfer planlaması.',accommodationNotes:'Anlaşmalı otel seçenekleri talebe göre koordine edilir.'}});
const doctorPresence=await prisma.doctor.findMany({take:4,orderBy:{createdAt:'asc'}});for(const [i,d] of doctorPresence.entries())await prisma.doctor.update({where:{id:d.id},data:{presenceStatus:i===0?'AVAILABLE':i===1?'ONLINE':i===2?'BUSY':'OFFLINE',presenceUpdatedAt:new Date()}});

}
main().finally(()=>prisma.$disconnect());
