"use client";import {useState} from "react";import {useRouter} from "next/navigation";export default function AgencyApplicationForm(){const [msg,setMsg]=useState("");const r=useRouter();async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));const res=await fetch("/api/agencies",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)});const j=await res.json();if(!res.ok){setMsg(j.error||"Başvuru gönderilemedi");return}setMsg("Sağlık turizmi profiliniz oluşturuldu ve doğrulamaya gönderildi.");setTimeout(()=>r.push(`/agency/${j.id}`),700)}
const Req = () => <span style={{color:'#ef4444', marginLeft:'4px', fontWeight:'bold'}}>*</span>;
return <form className="business-form premium-form" onSubmit={submit} style={{display:'flex', flexDirection:'column', gap:'16px'}}>
<label><span style={{fontWeight:'500'}}>Sağlık turizmi adı <Req/></span><input name="name" required placeholder="Örn: Alumas Sağlık Turizmi" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<div className="form-pair" style={{display:'flex', gap:'16px'}}>
<label style={{flex:1}}><span style={{fontWeight:'500'}}>Şehir <Req/></span><input name="city" required placeholder="Örn: İstanbul" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<label style={{flex:1}}><span style={{fontWeight:'500'}}>Telefon <Req/></span><input name="phone" required placeholder="0850 123 45 67" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
</div>
<label><span style={{fontWeight:'500'}}>E-posta <Req/></span><input name="email" type="email" required placeholder="iletisim@alumas.com" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<label><span style={{fontWeight:'500'}}>Web sitesi</span><input name="website" placeholder="https://www.alumas.com" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<label><span style={{fontWeight:'500'}}>TÜRSAB Belge No (Opsiyonel)</span><input name="tursabNo" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<label><span style={{fontWeight:'500'}}>Sağlık Turizmi Yetki Belge No (Opsiyonel)</span><input name="authorizationNo" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<label><span style={{fontWeight:'500'}}>Desteklenen diller</span><input name="languages" placeholder="Örn: Türkçe, English, Deutsch" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<label><span style={{fontWeight:'500'}}>Açıklama <Req/></span><textarea name="description" rows={5} required placeholder="Sağlık turizmi hizmetleri ve odaklandığı bölgeler hakkında bilgi..." style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
{msg&&<div className="inline-message" style={{padding:'12px', borderRadius:'8px', background: msg.includes('oluşturuldu') ? '#dcfce3' : '#fee2e2', color: msg.includes('oluşturuldu') ? '#166534' : '#991b1b', fontWeight:'500'}}>{msg}</div>}
<button className="primary" style={{padding:'14px', fontSize:'16px', fontWeight:'600', marginTop:'8px', borderRadius:'8px'}}>Sağlık turizmi başvurusu oluştur</button>
</form>}