"use client";import {useState} from "react";import {useRouter} from "next/navigation";
export default function BusinessApplicationForm(){const [type,setType]=useState("CLINIC"),[msg,setMsg]=useState("");const router=useRouter();async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const fileInput=f.querySelector('input[type="file"]') as HTMLInputElement;if(fileInput?.files?.[0]&&fileInput.files[0].size>4.5*1024*1024){setMsg('Dosya boyutu çok büyük (Maksimum 4.5 MB yüklenebilir).');return}setMsg("Gönderiliyor...");try{const r=await fetch("/api/organizations",{method:"POST",body:new FormData(f)});if(r.status===413){setMsg('Dosya boyutu çok büyük (Vercel sınırı 4.5 MB).');return}if(!r.ok){const t=await r.text();try{const j=JSON.parse(t);setMsg(j.error||"Başvuru gönderilemedi")}catch{setMsg(`Sunucu hatası (${r.status})`)}return}await r.json();setMsg("Başvurunuz alındı. Admin incelemesine gönderildi.");setTimeout(()=>router.push("/business"),700)}catch(err:any){setMsg(err.message||'Bir hata oluştu.')}}
const Req = () => <span style={{color:'#ef4444', marginLeft:'4px', fontWeight:'bold'}}>*</span>;
return <form className="business-form premium-form" onSubmit={submit} style={{display:'flex', flexDirection:'column', gap:'16px'}}>
<div className="org-type-select" style={{marginBottom:'12px'}}>{[["HOSPITAL","Hastane"],["CLINIC","Klinik"],["PHARMACY","Eczane"],["IMAGING_CENTER","Görüntüleme M."]].map(x=><button type="button" className={type===x[0]?"selected":""} key={x[0]} onClick={()=>setType(x[0])}>{x[1]}</button>)}</div>
<input type="hidden" name="type" value={type}/>
<label style={{fontWeight:'500'}}>Kurum adı <Req/></label><input name="name" required placeholder="Örn: Ayça Şirin Görüntüleme Merkezi" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0'}}/>
<div className="form-pair" style={{display:'flex', gap:'16px'}}>
<div style={{flex:1, display:'flex', flexDirection:'column'}}><label style={{fontWeight:'500', marginBottom:'4px'}}>Şehir <Req/></label><input name="city" required placeholder="Örn: Mersin" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0'}}/></div>
<div style={{flex:1, display:'flex', flexDirection:'column'}}><label style={{fontWeight:'500', marginBottom:'4px'}}>İlçe</label><input name="district" placeholder="Örn: Tarsus" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0'}}/></div>
</div>
<label style={{fontWeight:'500'}}>Açık Adres <Req/></label><input name="address" required placeholder="Mahalle, sokak, bina no vb." style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0'}}/>
<div className="form-pair" style={{display:'flex', gap:'16px'}}>
<div style={{flex:1, display:'flex', flexDirection:'column'}}><label style={{fontWeight:'500', marginBottom:'4px'}}>Kurumsal Telefon <Req/></label><input name="phone" required placeholder="05XX XXX XX XX" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0'}}/></div>
<div style={{flex:1, display:'flex', flexDirection:'column'}}><label style={{fontWeight:'500', marginBottom:'4px'}}>Kurumsal E-posta <Req/></label><input name="email" type="email" required placeholder="iletisim@kurum.com" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0'}}/></div>
</div>
<label style={{fontWeight:'500'}}>Web sitesi (İsteğe bağlı)</label><input name="website" placeholder="https://www.kurum.com" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0'}}/>
<label style={{fontWeight:'500'}}>Kurum Açıklaması</label><textarea name="description" rows={4} placeholder="Kurumunuz hakkında kısa bir bilgilendirme yazısı..." style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0'}}/>
<label style={{fontWeight:'500'}}>Ruhsat / Doğrulama belgesi (İsteğe bağlı)</label><input name="license" type="file" accept="application/pdf,image/jpeg,image/png" style={{padding:'8px', borderRadius:'8px', border:'1px dashed #cbd5e1', background:'#f8fafc', cursor:'pointer'}}/>
{msg&&<div className="inline-message" style={{padding:'12px', borderRadius:'8px', background: msg.includes('Başvurunuz alındı') ? '#dcfce3' : '#fee2e2', color: msg.includes('Başvurunuz alındı') ? '#166534' : '#991b1b', fontWeight:'500'}}>{msg}</div>}
<button className="primary" type="submit" style={{padding:'14px', fontSize:'16px', fontWeight:'600', marginTop:'8px', borderRadius:'8px'}}>Başvuruyu gönder</button>
</form>}
