"use client";import {useState} from "react";import {useRouter} from "next/navigation";
export default function DoctorOnboardingForm(){const [msg,setMsg]=useState("");const r=useRouter();async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMsg("Gönderiliyor...");const data=Object.fromEntries(new FormData(e.currentTarget));const res=await fetch("/api/onboarding/doctor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const j=await res.json();if(!res.ok){setMsg(j.error||"Profil oluşturulamadı");return}setMsg("Profil oluşturuldu. Doğrulama sonrası halka açık listede yayınlanacak.");setTimeout(()=>r.push("/doctor"),700)}
const Req = () => <span style={{color:'#ef4444', marginLeft:'4px', fontWeight:'bold'}}>*</span>;
return <form className="business-form premium-form" onSubmit={submit} style={{display:'flex', flexDirection:'column', gap:'16px'}}>
<label><span style={{fontWeight:'500'}}>Unvan <Req/></span><input name="title" placeholder="Örn: Prof. Dr. veya Uzm. Dyt." required style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<label><span style={{fontWeight:'500'}}>Uzmanlık alanı <Req/></span><input name="specialty" placeholder="Örn: İç Hastalıkları, Kardiyoloji" required style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<div className="form-pair" style={{display:'flex', gap:'16px'}}>
<label style={{flex:1}}><span style={{fontWeight:'500'}}>Şehir <Req/></span><input name="city" required placeholder="Örn: İstanbul" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<label style={{flex:1}}><span style={{fontWeight:'500'}}>Çalıştığı kurum / Bağımsız <Req/></span><input name="hospital" placeholder="Örn: Alumas Hastanesi veya Bağımsız" required style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
</div>
<label><span style={{fontWeight:'500'}}>Mesleki sicil / ruhsat no <Req/></span><input name="licenseNumber" required placeholder="Tescil veya sicil numaranız" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<label><span style={{fontWeight:'500'}}>Kısa biyografi <Req/></span><textarea name="bio" rows={5} required placeholder="Uzmanlığınız, eğitim geçmişiniz ve profesyonel ilgi alanlarınız hakkında kısa bir yazı..." style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
<label><span style={{fontWeight:'500'}}>Görüşme başlangıç fiyatı (₺)</span><input name="price" type="number" min="0" defaultValue="0" style={{padding:'12px', borderRadius:'8px', border:'1px solid #e2e8f0', marginTop:'6px'}}/></label>
{msg&&<div className="inline-message" style={{padding:'12px', borderRadius:'8px', background: msg.includes('oluşturuldu') ? '#dcfce3' : '#fee2e2', color: msg.includes('oluşturuldu') ? '#166534' : '#991b1b', fontWeight:'500'}}>{msg}</div>}
<button className="primary" style={{padding:'14px', fontSize:'16px', fontWeight:'600', marginTop:'8px', borderRadius:'8px'}}>Uzman profilimi oluştur</button>
</form>}