"use client";
import {useEffect,useMemo,useState} from "react";
type R={id:string;startsAt:string;endsAt?:string|null;flow?:string|null;symptoms:string[];note?:string|null};
const fmt=(d:string)=>new Date(d).toLocaleDateString('tr-TR');
export default function Page(){const [rows,setRows]=useState<R[]>([]),[message,setMessage]=useState("");const load=()=>fetch('/api/health/cycle').then(r=>r.json()).then(x=>setRows(Array.isArray(x)?x:[]));useEffect(()=>{load()},[]);
const stats=useMemo(()=>{const sorted=[...rows].sort((a,b)=>+new Date(a.startsAt)-+new Date(b.startsAt));const diffs=sorted.slice(1).map((r,i)=>(+new Date(r.startsAt)-+new Date(sorted[i].startsAt))/86400000).filter(n=>n>=15&&n<=60);const avg=diffs.length?Math.round(diffs.reduce((a,b)=>a+b,0)/diffs.length):null;const last=sorted.at(-1);const next=avg&&last?new Date(+new Date(last.startsAt)+avg*86400000):null;return {avg,last,next}},[rows]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMessage("");const form=e.currentTarget,f=new FormData(form);const res=await fetch('/api/health/cycle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({startsAt:f.get('startsAt'),endsAt:f.get('endsAt')||null,flow:f.get('flow')||null,symptoms:String(f.get('symptoms')||'').split(',').map(x=>x.trim()).filter(Boolean),note:f.get('note')||null})});const x=await res.json();if(!res.ok){setMessage(x.error||'Kayıt eklenemedi');return}form.reset();setMessage('Kayıt eklendi.');load()}
async function remove(id:string){if(!confirm('Bu döngü kaydı silinsin mi?'))return;const r=await fetch('/api/health/cycle?id='+encodeURIComponent(id),{method:'DELETE'});if(r.ok)load()}
return <div className="page"><div className="page-title"><span className="kicker">Kadın sağlığı</span><h1>Regl Takibi</h1><p>Döngü tarihlerini, akış bilgisini, belirtileri ve kişisel notlarını kaydet.</p></div><div className="cycle-note">Tahmini sonraki başlangıç yalnız geçmiş kayıtlarının ortalamasına dayalı kişisel planlama bilgisidir; doğum kontrolü, gebelik değerlendirmesi, tanı veya tedavi amacıyla kullanılmamalıdır.</div><div className="cycle-summary"><div><span>Son başlangıç</span><strong>{stats.last?fmt(stats.last.startsAt):'—'}</strong></div><div><span>Ortalama döngü</span><strong>{stats.avg?`${stats.avg} gün`:'—'}</strong></div><div><span>Tahmini sonraki</span><strong>{stats.next?stats.next.toLocaleDateString('tr-TR'):'—'}</strong></div></div><form className="panel v24-form" onSubmit={submit}><label>Başlangıç<input name="startsAt" type="date" required/></label><label>Bitiş<input name="endsAt" type="date"/></label><label>Akış<select name="flow"><option value="">Seç</option><option>Hafif</option><option>Orta</option><option>Yoğun</option></select></label><label>Belirtiler<input name="symptoms" placeholder="Kramp, baş ağrısı, şişkinlik…"/></label><label>Not<textarea name="note" placeholder="Kişisel not"/></label><button className="primary">Kaydet</button></form>{message&&<div className="inline-message">{message}</div>}<section className="panel"><h2>Geçmiş kayıtlar</h2>{rows.map(r=><div className="share-row" key={r.id}><div><b>{fmt(r.startsAt)} {r.endsAt?`– ${fmt(r.endsAt)}`:''}</b><small>{r.flow||'Akış belirtilmedi'}{r.symptoms?.length?` · ${r.symptoms.join(', ')}`:''}{r.note?` · ${r.note}`:''}</small></div><div className="cycle-actions"><button className="danger-link" onClick={()=>remove(r.id)}>Sil</button></div></div>)}{!rows.length&&<div className="empty">Henüz kayıt yok.</div>}</section></div>}
